# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

    pool: 
      vmImage: ubuntu-18.04
    container:
      image: teaclave/teaclave-trustzone-sdk-build:0.2.1
    steps:
    - script: |
        git clone https://github.com/apache/incubator-teaclave-trustzone-sdk.git
        cd incubator-teaclave-trustzone-sdk
        ./setup.sh
        git submodule update --init -- optee
      displayName: 'Checkout repository'
    - script: |
        sudo cp /root/.bashrc $HOME/.bashrc &&
        ln -sf /root/.rustup ~/.rustup &&
        ln -sf /root/.cargo ~/.cargo
      displayName: 'Setting up $HOME'
    - script: |
        cd incubator-teaclave-trustzone-sdk &&
        source environment
        make optee &&
        . ~/.cargo/env &&
        rustup default nightly-2019-07-08 &&
        make examples
      displayName: 'Building'
    - script: |
        cd incubator-teaclave-trustzone-sdk/ci &&
        ./ci.sh
      displayName: 'Run tests and examples'