# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


    pool: Default
    container:
      image: teaclave/teaclave-trustzone-sdk-build:0.2.1
    steps:
    - script: |
        echo Hello, world!
        git clone git@github.com:apache/incubator-teaclave-trustzone-sdk.git
        cd incubator-teaclave-trustzone-sdk
        ./setup.sh
        git submodule update --init -- optee
      displayName: 'Checkout repository'
    - script: |
        cp /root/.bashrc $HOME/.bashrc &&
        ln -sf /root/.rustup ~/.rustup &&
        ln -sf /root/.cargo ~/.cargo
      displayName: 'Setting up $HOME'
    - script: |
        source environment &&
        make optee &&
        . ~/.cargo/env &&
        rustup default nightly-2019-07-08 &&
        make examples
      displayName: 'Building'
    - script: |
        cd ci && ./ci.sh
      displayName: 'Run tests and examples'
